### PR TITLE
Change non-BIDS dataset layout

### PR DESCRIPTION
**Pull request by mih**
This implements a change suggested by @satra in https://github.com/datalad/datalad-ukbiobank/pull/31#issuecomment-626319689 (which makes this my first recursive PR, cool!)

It primarily solves the problem that some ZIP files for data records contain obfuscated names that make at hard to reconnect to a specific data record (ZIP that contain only numbered PNG, in no subdirectory). Given the complexity and variabilty it makes sense to extract ZIP file content into a directory named after the data record ID.

To avoid needless complexity in the path names, the `instance-<id>` top-level directories have been removed too, and the BIDS mapping setup was adjusted accordingly.

This leads to the following layout:

```
<filename> # for non zip content
<filename-without.zip>/[unzipped content]
```
This should make it more natural to work with this layout, as it removes the arbitrarily named, additional `instance-<int>` session directory.

Fixes gh-29

TODO (need not be in this PR):
- [ ] Adjust BIDS mapping (still needs data record prefix for `raw/`
- [ ] Provide BIDS mapping for the datarecords that @satra used to demonstrate the issue, or provide a catch-all `non-bids` mapping

### CODE REVIEW

**Comment by mih** [comment]
@loj Can you please have a look at https://github.com/datalad/datalad-ukbiobank/pull/31/commits/af74eef8e1e4838a07016fc5cbef0a80975ceacd -- we need a similar change with the datarecord that provides the files in `raw/`

@satra This implement one aspect of the changes we talked about. If that looks OK to you, we can proceed and integrate #30 

Here is a sketch of the output structure (no BIDS normalization) with this PR.
```
instance-2
├── 20227_0
│   └── fMRI
├── 20249_0
│   └── fMRI
│       └── tfMRI.feat
├── 20250_0
│   ├── dMRI
│   └── fieldmap
├── 20251_0
│   └── SWI
├── 20252_0
│   └── T1
└── 20253_0
    └── T2_FLAIR
```

**Comment by satra** [comment]
@mih - do we want to move the `_<array_id>` to something embedded lower towards the leaf?

**Comment by mih** [comment]
This would mean to alter the filenames of the ZIP file content, and potentially breaking existing or future code that assumes an organization as provided by UKB. Unless there is a superb reason for it, I'd say we shouldn't do that.

**Comment by satra** [comment]
the format of the zip file or other content is:

`<filename> = <eid>_<field>_<instance>_<array_id>.<extension>`.  

the generic output could be: `<eid>/ses-<instance>/<field>/<array_id>/[<filename> | unzipped content]` and could be remapped as necessary to bids/bids-like. 

so it simply takes <array_id> as an index into the field. this allows access by field, so if a field gets removed in a future update, we can also simply remove the field as a whole as well.

in the current format you are already going from `<field>_<instance>_<array_id>` to `<field>_<array_id>`, which is already different from ukb. and the above form doesn't change the formatting of the filename simply where it is dumped in a hierarchy.

if not considering bids-like, i would be completely fine with even this:
```
<eid>/<filename>  # for non zip files
<eid>/<field>_<instance>_<array_id>/[unzipped content] # for zip files
```

**Comment by satra** [comment]
just to clarify, i'm using `<eid>` for clarity, i do understand that `<eid>` itself is a datalad dataset.

**Comment by mih** [comment]
My brain is slow. I am filling your templates with a real case to see what I am missing:

> the format of the zip file or other content is:
> 
> `<filename> = <eid>_<field>_<instance>_<array_id>.<extension>`.

`1002532_25747_2_0.adv`

> the generic output could be: `<eid>/ses-<instance>/<field>/<array_id>/[<filename> | unzipped content]` and could be remapped as necessary to bids/bids-like.

`ses-2/25747/0/1002532_25747_2_0.adv`

The session dir makes BIDS mapping practical, so that I acknowledge (although it could probably be swapped with another strategy). Which purpose do the other dirs serve?

> so it simply takes <array_id> as an index into the field. this allows access by field, so if a field gets removed in a future update, we can also simply remove the field as a whole as well.

`ses-2/25747_0.adv`

How is access by field not possible in this case?

Here is a (fake) case of multi-item array records (I strip the `eid`)

`ses-2/12345/0/12345_2_0.adv`
`ses-2/12345/1/12345_2_1.adv`

What makes this superior to:

`ses-2/12345_0.adv`
`ses-2/12345_1.adv`

> in the current format you are already going from `<field>_<instance>_<array_id>` to `<field>_<array_id>`, which is already different from ukb. and the above form doesn't change the formatting of the filename simply where it is dumped in a hierarchy.

I acknowledge that my setup changes the names. However, your's does too (there is no `.zip` file anymore), and it duplicates information. So in order to reach a target file, you still need to decompose into `<field>`, `<instance>`, `<array_id>` (true in both scenarios).

I suspect you have a use/consumption case in mind that did not cross mine yet.

**Comment by satra** [comment]
i was simply responding to this:

> potentially breaking existing or future code that assumes an organization as provided by UKB

so to go with that statement/sentiment, i would say the closest match would be something like this:

```
<eid>/<filename>  # for non zip files
<eid>/<filename>/[unzipped content] # for zip files
```

i am ok with any organization from a coding standpoint. just didn't understand why <array_id> was special to include in field - especially since for bids we would want it to go into `run-<index>`

in terms of use case, while "bids" doesn't support my oct/fundus/accelerometer data, nothing would prevent me from organizing them like bids.

```
<eid>/<ses-id>/<field>/<filename>
<eid>/<ses-id>/<field>/<filename>/[unzipped content]
```
so concretely for oct (field 21018) this would look like this:
```
<eid>/ses-0/21018/*_21018_0_0/[png_files]
<eid>/ses-0/21018/*_21018_0_1/[png_files]
```
which is closer to bids than:
```
<eid>/ses-0/21018_0/[png_files]
<eid>/ses-0/21018_1/[png_files]
```

ps. in the bids rendering `<field>` becomes func/anat/Freesurfer, etc.,. for bids it would be nice to be able to create a mapping a between <filename> and remapped filename somewhere.

**Comment by mih** [comment]
> i was simply responding to this:
> 
> > potentially breaking existing or future code that assumes an organization as provided by UKB

Ah, ok. So that was a misunderstanding, following my misunderstanding of:

> do we want to move the _<array_id> to something embedded lower towards the leaf?

which I interpreted as "modify the filenames of ZIP file *content*, by appending an array suffix".

So we are largely in agreement, and we are merely debating style, it seems.

I have to confess that "X is closer to bids than Y" is not something that I have in my list of criteria regarding the layout of the non-BIDS datasets. I guess, I want a compact representation that feels sensible for people familiar with the UKB nomenclature, while not being absolutely incompatible (or technical disaster) regarding a mapping to BIDS. I will give this some more thought.

**Comment by satra** [comment]
>  I guess, I want a compact representation that feels sensible for people familiar with the UKB nomenclature

here is a suggestion to add to your thoughts.

if `--bids`: (assuming whoever uses this flag is not doing so randomly :) )

```
B: 
<eid>/<ses-id>/<field>/<filename> # for non zip content
<eid>/<ses-id>/<field>/<filename>/[unzipped content]
```

else:

```
NB:
<eid>/<filename> # for non zip content
<eid>/<filename>/[unzipped content]
```

think of `B:` as a view of `NB:` (i hear datalad will soon support view re-mapping, so bids branch could indeed be a view mapping of non-bids branch)

**Comment by loj** [comment]
> @loj Can you please have a look at af74eef -- we need a similar change with the datarecord that provides the files in raw/ Thx!

@mih I looked into this and tried to figure out where this `raw` dir is coming from. The origin of these mappings (https://git.fmrib.ox.ac.uk/falmagro/UK_biobank_pipeline_v_1/blob/master/bb_data/UKBB_to_BIDS.json) is part of the [imaging processing pipeline]( https://www.sciencedirect.com/science/article/pii/S1053811917308613?via%3Dihub#appsec1) used for the UKB. After the dicom to nifti conversion, their "file manager" sorts out the possible problems with the number of files found per modality and renames them according to their [logical rules](https://ars.els-cdn.com/content/image/1-s2.0-S1053811917308613-mmc1.pdf). I think this is where the `raw` dir comes in, and images like `T1_notNorm` are sorted into it.

My understanding from the [UKB Imaging Documentation](https://biobank.ctsu.ox.ac.uk/crystal/crystal/docs/brain_mri.pdf), is that the raw data for each modality type is included in the nifiti downloads along with processed data files. Indeed, we do have raw data for each modality, but I searched for the above files (`T1_notNorm`, `T2_FLAIR_notNorm`, `AP_SBREF`, `PA_SBREF`, `SWI_TOTAL_MAG_notNorm_TE2`, `SWI_TOTAL_MAG_notNorm`) in our nifti downloads and did not find them. 

My conclusions:
* I don't believe there is a separate data record for these other "raw" images. 
* It seems that these particular images are not included nifti downloads, and perhaps are only included in the dicom downloads.

My opinion is that we don't need to include these files in the mapping.

**Comment by mih** [comment]
Thx @loj

**Comment by satra** [comment]
@mih - any further thought to [these thoughts](https://github.com/datalad/datalad-ukbiobank/pull/31#issuecomment-626319689)

**Comment by satra** [comment]
ping @mih - should i attempt a PR? we are a little stuck at present because of this issue. just trying to figure out whether we should fork a hack or wait. if the latter any estimates?

**Comment by mih** [comment]
Sorry, didnt work out this week. It is next up on the TODO for next week. If you can wait a few more days it would make sense. If not, that is fine too, of course.

**Comment by satra** [comment]
thanks @mih - i can wait a few more days. 

we are now accumulating a map of data we have to the fields. so that we don't have to re-download (see #26). but it would still be good to have the download url be added as part of git-annex remote. (i had not checked if that is being done).

**Comment by mih** [comment]
> thanks @mih - i can wait a few more days.

I am on it now.

> we are now accumulating a map of data we have to the fields. so that we don't have to re-download (see #26). but it would still be good to have the download url be added as part of git-annex remote. (i had not checked if that is being done).

What do you mean by download URL? We record the execution of `ukbfetch`, but do not introspect what it is doing internally. Do you have a more explicit approach in mind?

```

```

**Comment by mih** [comment]
@satra I have force-pushed (and adjusted the toplevel comment) to reflect the changes you requested in https://github.com/datalad/datalad-ukbiobank/pull/31#issuecomment-626319689 -- for the non-bids layout case. There have been no changes for the BIDS case yet. I am undecided on that one, but I think I am fine with any setup under `non-bids` for those (PR welcome).

**Comment by satra** [comment]
> What do you mean by download URL? We record the execution of ukbfetch, but do not introspect what it is doing internally. Do you have a more explicit approach in mind?

i thought each ukbfetch generated a download url (thereby creating a special remote), but i was mistaken. the current approach is fine.

**Comment by mih** [comment]
Once this PR is merged (in one way or another), we can expand the test that came with #35 to actually verify dataset layout.

**Comment by satra** [comment]
@mih -  are you waiting on something specific (hopefully not from me) to merge this PR?

**Comment by satra** [comment]
also @mih - does it make sense to have two branches incoming-bids and incoming-processed?

so everything goes from `incoming->incoming-processed->incoming-bids`

where `incoming-processed` looks like the option discussed here. it should not create any additional storage requirements and would give users both views to work with?

**Comment by mih** [comment]
> @mih - are you waiting on something specific (hopefully not from me) to merge this PR?

I was waiting for you ;-)

> does it make sense to have two branches incoming-bids and incoming-processed?

It does make sense, and it wouldn't require more resources. Let's do it outside this PR though ;-)

**Comment by satra** [comment]
> I was waiting for you ;-)

in that case, i have tested this branch and it does what it says it does :) LGTM.

**Pull request merged**
