### PR TITLE
Fix two inconveniences re dataset maintenance

### LINKED ISSUE #54: incoming branch is not using standard .gitattributes from `datalad create`
The master branch has

```
* annex.backend=MD5E                                                                       
**/.git* annex.largefiles=nothing                                                          
```

But this is no present in the incoming branch, because we build it from scratch. This can lead to sudden changes in the backend usage, depending on the config supplied from outside a dataset.

### LINKED ISSUE #55: Detection of BIDS-mode does not work with fresh clones
The detection of an `incoming-bids` branch

https://github.com/datalad/datalad-ukbiobank/blob/46c743ef8fce01c6c321c7943533a9a0c420795f/datalad_ukbiobank/update.py#L248

relies on the assumption of it being locally present. However, in a fresh clone this will not be the case. We should also check remote branches.

### LINKED ISSUE #68: Still usage of hard-coded 'master' branch
Recent fixes by @bpoldrack did not catch all cases.

### PR DESCRIPTION
**Pull request by mih**
See commit messages for details.

Fixes #54 
Fixes #55 
Fixes #68

### CODE REVIEW

**Comment by mih** [comment]
This is good now.

**Comment by loj** [comment]
I tested this out a bit, and a situation that still creates a problem for me is running `ukb-update` in a fresh clone. It will fail with 
```
[ERROR  ] Unknown commit identifier: incoming [gitrepo.py:get_hexsha:1847] (ValueError) 
```
Specifically it fails at line 151 (`initial_incoming = repo.get_hexsha('incoming')`)

The situation I see this coming up in is if you don't need to re-initialize the cloned dataset to add datatypes, and just want to run `ukb-update` to check for changes to the existing data.

To reproduce:
```
datalad create sub-1002532
cd sub-1002532
datalad ukb-init --bids 1002532 20227_2_0
datalad ukb-update --keyfile <path_to_key> --merge

cd ../
datalad clone sub-1002532 testclone
cd testclone
datalad ukb-update --keyfile <path_to_key> --merge
```

Otherwise, the changes to address #54 and #68 look good. :-)

**Comment by mih** [comment]
Thanks! I have pinpointed the failure with a unittest. Will look for a fix and update this PR.

**Comment by mih** [comment]
Fix pushed, passes for me locally.

**Comment by loj** [comment]
Cool! It works for me as well. :-)

**Comment by mih** [comment]
Alrighty, so let's be done with this! Thx!

**Pull request merged**
