### PR TITLE
DOCS: update with additional content

### PR DESCRIPTION
**Pull request by loj**
I've added content that gives an overview of the concepts/terms and provides some examples.

### CODE REVIEW

**Comment by adswa** [comment]
This is really really cool!

**Comment by mih** [comment]
Awesome! Thx much!

**Comment by loj** [comment]
The appveyor fail seems unrelated, but is this something that needs to be addressed elsewhere?

**Comment by mih** [comment]
Yes, true. I will take care of that.

**Comment by mih** [comment]
Opened #67 to fix the build failure.

**Comment by mih** [comment]
I have merged the fixed master into this PR. There is also a preview build from readthedocs for it now (click the link in the checks).

**Comment by mih** [comment]
Awesome contribution!

**Pull request merged**
