### PR TITLE
MNT: Remove eval_file_type (removed from core) from code base

### PR DESCRIPTION
**Pull request by adswa**
https://github.com/datalad/datalad/pull/6738 removed the deprecated and almost unused internal `eval_file_type` parameter. This companion PR removes the (effectless) use of this parameter from ``datalad-ukbiobank`` (a change I regard as needed to interoperate with 0.16.4 and higher, but backwards compatible).

### CODE REVIEW

**Comment by adswa** [comment]
ping @loj @mih

**Comment by adswa** [comment]
Yes, see #82, a wrong fix in #85, and the consecutive WIP PR in core

**Review by bpoldrack — APPROVED** [review]
Ah, right.

Unrelated then - take my approval :)

**Comment by mih** [comment]
We need to get `pytest` to make the CI run again after datalad 0.17. Will push shortly.

**Comment by mih** [comment]
https://github.com/datalad/datalad-ukbiobank/pull/86 shows that this is safe to merge. Thx!

**Pull request merged**
