### PR TITLE
WIP: add freesurfer recon fields

### PR DESCRIPTION
**Pull request by satra**
@mih - haven't studied the code, but this field is freesurfer recon and looks like this when currently unzipped.

```
./instance-2
./instance-2/FreeSurfer
./instance-2/FreeSurfer/stats
./instance-2/FreeSurfer/surf
./instance-2/FreeSurfer/label
./instance-2/FreeSurfer/mri
./instance-2/FreeSurfer/scripts
```
it would be nice if i could create the pattern.

`{subj}/ses-{instance}/Freesurfer/{subj}/{stats, surf, label, mri, scripts}`

this would allow setting the `SUBJECTS_DIR` to `{subj}/ses-{instance}/Freesurfer/`

i think this is the only field in my list amongst the imaging fields that's not in this mapping file.

### CODE REVIEW

**Comment by mih** [comment]
If we go ahead with #31 the target might need a trailing slash. Otherwise this looks fine to me. Thx!

**Comment by mih** [comment]
In https://github.com/datalad/datalad-ukbiobank/pull/35 I have provided a simplistic way to test proper placement of datarecords.

If you add some info about the content of this datarecord ZIP file to https://github.com/datalad/datalad-ukbiobank/blob/master/datalad_ukbiobank/tests/__init__.py#L10
we can compose a simple check. Alternatively you can post a dump of the filenames in here, and I'll take care of it.

**Comment by satra** [comment]
@mih - do you really want all of the 276 files to map or just the top level directories as listed?

```
"20263_2_0": {
...
}
```

the zip file expands to, with each folder containing many files as per usual freesurfer output.
```
./instance-2
./instance-2/FreeSurfer
./instance-2/FreeSurfer/stats
./instance-2/FreeSurfer/surf
./instance-2/FreeSurfer/label
./instance-2/FreeSurfer/mri
./instance-2/FreeSurfer/scripts
```

**Comment by mih** [comment]
@satra That should be enough to act on it. Thx!

**Comment by mih** [comment]
I think I only now realize what the core issue is here:

`/ses-{instance}/Freesurfer/{subj}/{stats, surf, label, mri, scripts}` would now translate to:

`20263_2_0/Freesurfer/{subj}/{stats, surf, label, mri, scripts}`

which means injecting `/subj/` in the middle of content that comes from a ZIP.

Need to think about this.

**Comment by satra** [comment]
> I think I only now realize what the core issue is here

do you mean this specifically for bids or general?

if general, i can easily create a freesurfer_subjects directory that maps {subj} to this internal location.

`/FSSubjects_dir/{subj}  links to <eid>/20263_2_0/Freesurfer/`

so this would be outside of the datalad organization for each participant.

**Comment by satra** [comment]
should this be closed?

**Comment by mih** [comment]
Yes, let's close this. Sorry that I dropped the ball on this issue.

**Pull request closed without merging**
